 # Arreglos y operaciones vectoriales con [NumPy](http://www.numpy.org/)


NumPy es un paquete de computación científica con Python que provee:

- Un objecto contenedor muy versatil: arreglo N-dimensional `ndarray`
- Funciones capaces de hacer *broadcasting*
- Módulos para algebra lineal, Transformada de Fourier, generación de número aleatorios, entre otros
- Herramientas para integrar código C/C++


**Instalación**
    
Con nuestro ambiente conda activado:

    conda install numpy
    
Esto instalará numpy y las librerías de bajo nivel BLAS y MKL

Luego importamos usando

In [1]:
import numpy as np
print("Version: ", np.__version__)

Version:  1.21.2


## Objeto ndarray (alias array)

Una lista `lista` de Python es un tipo de arreglo donde cada elemento puede ser de tipo diferente

:::{warning}

En general es muy ineficiente hacer cálculos numéricos usando listas

:::

Para cálculos numéricos eficientes utilizaremos el objeto `ndarray` de NumPy, que corresponde a un **arreglo n-dimensional de tipo fijo**

La siguiente figura muestra arreglos de Numpy de una, dos y tres dimensiones, respectivamente

<img src="img/ndarray.png" width="500">


Podemos crear un ndarray a partir de 

- una lista o tupla usando `np.array`
- funciones generadoras de NumPy, por ejemplo `np.linspace`, `np.zeros`, etc
- un fichero, por ejemplo usando [`np.genfromtxt`](https://numpy.org/devdocs/user/basics.io.genfromtxt.html) (aunque es preferible utilizar `pandas` en estos casos


In [2]:
# Supongamos que tenemos la siguiente lista de listas
L = [[0, 1, 2], [3, 4, 5]]
print("L es un", type(L))

L es un <class 'list'>


In [3]:
# Podemos transformarla a ndarray con
A = np.array(L)
print("A es un", type(A))
display(A)

A es un <class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5]])

**Atributos básicos de un ndarray**

- El atributo `ndim` es un entero que nos indica el número de dimensiones o ejes del arreglo
- El atributo `shape` es una tupla de entero que nos indica el tamaño del arreglo en cada una de sus dimensiones
- El atributo `dtype` nos indica el tipo del arreglo

En este caso

In [9]:
f"A tiene {A.ndim} dimensiones"

'A tiene 2 dimensiones'

In [10]:
len(A.shape) == A.ndim

True

In [17]:
for d in range(A.ndim):
    print(f"La dimensión {d} tiene largo {A.shape[d]}")

La dimensión 0 tiene largo 2
La dimensión 1 tiene largo 3


In [19]:
f"El arreglo es de tipo {A.dtype}"

'El arreglo es de tipo int64'

Los tipos de dato estándar de NumPy son:

- Enteros: int8, int16, int32, int64
- Enteros sin signo: uint8, uint16, uint32, uint64
- Flotantes (reales): float16, float32, float64, float128
- Números complejos: complex64, complex128, complex256
- Booleanos: Bool

Podemos forzar el tipo al momento de crear usando el argumento `dtype`

In [4]:
display(np.array(L, dtype=np.int16))
display(np.array(L, dtype=np.float32))

array([[0, 1, 2],
       [3, 4, 5]], dtype=int16)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

**Funciones generadoras de ndarray**

Existen algunas funciones de NumPy que permiten crear directamente arreglos con ciertas propiedades

Algunos ejemplos útiles son:

In [25]:
np.zeros(shape=(2, 3), dtype=np.int64) # Arreglo lleno de ceros

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones(shape=(2, 3), dtype=np.float32) # Arreglo lleno con unos

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [27]:
np.full(shape=(2, 3), fill_value=np.pi) # Arreglo lleno con un valor arbitrario

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

También existen versiones de estas funciones que copian el tamaño y tipo de otro ndarray

In [29]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

Las siguientes funciones son muy útiles cuando necesitamos crear un rango lineal o logarítmico usando

Se especifica el inicio, el fin y el paso o cantidad de elementos:

In [30]:
np.arange(start=0, stop=5, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
np.linspace(start=0, stop=10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.logspace(start=-1, stop=1, num=5)

array([ 0.1       ,  0.31622777,  1.        ,  3.16227766, 10.        ])

## Manipulación de matrices y vectores

Es usual que antes de operar un ndarray necesitemos cambiar su tamaño o número de dimensiones

Algunas operaciones típicas para modificar la forma de un arreglo son: `reshape`, `tile`, `repeat`, `ravel` y `transpose`

`reshape` reorganice las dimensiones de un arreglo pero debe preservar el tamaño

In [34]:
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [35]:
np.reshape(A, (3, 2)) # Convierte 6 a 3x2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
np.reshape(A, (2, 3)) # Convierte 6 a 2x3

array([[0, 1, 2],
       [3, 4, 5]])

`tile` repite el arreglo en una dirección dada

In [37]:
np.tile(A, (4, 1)) # Repite 4 veces en la dirección de las filas

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [38]:
np.tile(A, (1, 2)) # Repite 2 veces en la dirección de las columnas

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

`repeat` repite cada elemento en una dirección o eje dado

In [39]:
np.repeat(A, 2) # Cada elemento aparece dos veces 

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [41]:
# Cada elemento/fila aparece dos veces en la dirección de las columnas
np.repeat(A.reshape(3, 2), 2, axis=1)

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

`ravel` es una función que aplana el ndarray y retorna un arreglo de una dimensión

In [44]:
# Convierte una matriz de 3x3 en un arreglo de 9
np.ravel(np.zeros(shape=(3, 3)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

`transpose` puede utilizarse para intercambiar la posición de los ejes/dimensiones de un ndarray

Tiene el mismo significado de la trasposición matricial

<img src="img/transpose.jpg" width="300">

Por ejemplo:

In [45]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.transpose(A) # Equivalente a A.transpose() o A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`transpose` puede usarse en ndarrays de cualquier dimensionalidad

Podemos usar el argumento `axes` para especificar cuales dimensiones se van a intercambiar

(Opcionalmente podemos usar la función `np.swapaxes()` para obtener le mismo efecto)

In [47]:
A = np.arange(8).reshape(2, 2, 2)
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
np.transpose(A, axes=(0, 2, 1))

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

**Agregar dimensiones a un arreglo**

En algunas ocasiones nos interesará extender un arreglo, agregándole dimensiones

Consideremos el siguiente arreglo unidimensional

In [49]:
A = np.array([0, 1, 2, 3, 4]) 
print("Dimensión:", A.ndim, ", Tamaño: ", A.shape)

Dimensión: 1 , Tamaño:  (5,)


Como vimos antes podemos agregar una dimensión usando `reshape`, pero otra forma más simple es usando `np.newaxis` (un alias de `None`)

Si queremos agregarle una dimensión al arreglo anterior podemos hacerlo a la derecha o a la izquierda

Por ejemplo agregarle una dimensión a la derecha creará una matriz de $N\times1$ o vector columna

In [50]:
Amod = A[:, np.newaxis]
display(Amod)
print("Dimensión:", Amod.ndim, ", Tamaño: ", Amod.shape)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Dimensión: 2 , Tamaño:  (5, 1)


Mientras que agregarle una dimensión a la izquierda creará una matriz de $1\times N$ o vector fila

In [51]:
Amod = A[np.newaxis, :]
display(Amod)
print("Dimensión:", Amod.ndim, ", Tamaño: ", Amod.shape)

array([[0, 1, 2, 3, 4]])

Dimensión: 2 , Tamaño:  (1, 5)


Algunas operaciones útiles para combinar arreglos son: `concatenate`, `vstack`, `hstack`

`concatenate` es más general que las dos últimas

In [58]:
A = np.arange(5).reshape(1, 5) 
B = np.ones(shape=(1, 5)) 
A, B

(array([[0, 1, 2, 3, 4]]), array([[1., 1., 1., 1., 1.]]))

In [59]:
np.concatenate((A, B), axis=0) # Combinar en eje filas

array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.concatenate((A, B), axis=1) # Combinar en eje columnas

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.]])

In [61]:
np.vstack((A, B)) # Combina siempre en fila

array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.hstack((A, B)) # Combina siempre en columna

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.]])

## Indexación y *slicing*

Al igual que otros contenedores de Python los ndarray soportan *slicing*

:::{note}

Slicing es crear una arreglo a partir de una indexación sobre otro arreglo

:::

Sea por por ejemplo:

In [63]:
L = [[0, 1, 2], [3, 4, 5]]
A = np.array(L)
A

array([[0, 1, 2],
       [3, 4, 5]])

Para acceder al elemento en la segunda fila y primera columna usaríamos

In [64]:
L[1][0]

3

En cambio en Numpy utilizamos

In [65]:
A[1, 0]

3

El ndarray nos da mucha flexibilidad para hacer slicing

In [66]:
A[:, 1] # Retorna la segunda columna

array([1, 4])

In [67]:
A[0, :] # Retorna la primera fila 

array([0, 1, 2])

In [68]:
A[1, ::2] # Retorna los elementos de la primera fila y columnas pares

array([3, 5])

In [69]:
A[-1, -2] # Retorna los elementos de la ultima fila y penultima columna

4

También podemos usar arreglos de enteros para indexar otro arreglo (*fancy indexing*)

In [70]:
ix = np.array([0, 0, 1])
iy = np.array([0, 1, 1])
A[ix, iy] # Elementos [0,0], [0,1] y [1,1]

array([0, 1, 4])

También podemos indexar usando un arreglo de booleanos

In [71]:
A = np.array([0, 2, 1, 3, 4])
B = np.array([True, False, False, True, True])
display(A[B])

array([0, 3, 4])

La siguiente figura muestra de forma esquemática varios ejemplos de slices

<img src="img/slicing.png" width="700">

:::{warning}

Algunas operaciones sobre arreglos no hacen copias (usan referencias)

:::

En particular cuando hacemos un slice, estamos modificando el arreglo original

In [72]:
A = np.arange(100).reshape(10, 10)
B = A
B is A

True

Si modifico A se ve reflejado en B

In [73]:
A[:5, :5] = 100
display(B)

array([[100, 100, 100, 100, 100,   5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100,  15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100,  25,  26,  27,  28,  29],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

Modificaciones en subarreglos (vistas) también son referenciadas

In [74]:
A = np.arange(100).reshape(10, 10)
B = A[:5, :5]
display(B is A)
B[:, :] = 100
display(A)

False

array([[100, 100, 100, 100, 100,   5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100,  15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100,  25,  26,  27,  28,  29],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

Si queremos evitar este comportamiento se puede forzar la creación de una copia con el método `copy()`

In [75]:
B = A.copy()
A[0, 0] = 0
display(B[0])

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

## Operaciones sobre ndarray

### Operaciones aritméticas y *Broadcasting* 

Los ndarray soportan las operaciones aritméticas básicas

- Suma:  +, +=
- Resta: -, -=
- Multiplicación:  *,*= 
- División: /, /=
- División entera: //, //=
- Exponenciación: ** , **=

Estas operaciones tienen un comportamiento element-wise (elemento a elemento), es decir

$$
\pmatrix{0 & 1 \\2 & 3 } \cdot \pmatrix{1 & 5 \\2 & 2 } = \pmatrix{0 & 5 \\4 & 6 }
$$

Veamos algunos ejemplos:

In [76]:
N = 3
A = np.eye(N)
B = np.ones(shape=(N, N))
A, B

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [77]:
A + B 

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [78]:
A*B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

:::{note}

El operador * no corresponde a la multiplicación de matrices sino a la multiplicación elemento por elemento

:::

**Broadcasting**

Cuando los ndarray que estamos operando no son del mismo tamaño se hace un *broadcast*

Por ejemplo si operamos una constante con un arreglo, la constante se opera con cada elemento del arreglo

In [79]:
A - 1

array([[ 0., -1., -1.],
       [-1.,  0., -1.],
       [-1., -1.,  0.]])

Las siguientes son las reglas automáticas de broadcasting

1. Si dos arreglos son de dimensiones distintas la dimensión del más pequeño se agranda con "1"s **por la izquierda**
1. Si dos arreglos tienen tamaños ditintos, el que tiene tamaño "1" se estira en dicha dimensión
1. Si en cualquier dimensión los tamaños son distintos y ninguno es igual a "1" ocurre un error


<img src="img/broadcast.png" width="550">

Imagen tomada del [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/06.00-figure-code.html#Broadcasting)

Observe los siguientes ejemplos y reflexione sobre las reglas de broadcast que se está aplicando en cada caso

In [80]:
C = np.arange(N)
B = np.ones(shape=(N, N))
C, B

(array([0, 1, 2]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [81]:
B+C

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [82]:
B + C.reshape(-1, 1)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [83]:
C.reshape(1, N) + C.reshape(N, 1)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

**Operaciones matriciales**

Antes dijimos que la multiplicación con `*` se realiza elemento a elemento

Para realizar una multiplicación matricial propiamente tal podemos usar `dot` o el operador `@`

In [84]:
A = np.arange(4).reshape(2, 2)
B = np.arange(4)[::-1].reshape(2, 2)
A, B 

(array([[0, 1],
        [2, 3]]),
 array([[3, 2],
        [1, 0]]))

Note la diferencia:

In [85]:
A*B

array([[0, 2],
       [2, 0]])

In [86]:
np.dot(A, B)

array([[1, 0],
       [9, 4]])

Otras operaciones matricionales útiles son:

- `np.inner` que calcula el producto escalar o producto interno
- `np.outer` que calcula el producto externo
- `np.cross` que calcula  cruz

El módulo  [`linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html) de NumPy contiene muchas más funciones de álgebra lineal que nos permiten 

- Calcular matriz inversa, determinantes y trazas
- Resolver sistemas lineales
- Factorizar matrices
- Calcular valores y vectores propios

entre otros. Este módulo será estudiando en una lección siguiente

### Operaciones de reducción

Una **reducción** es una operación que **agrega** los valores de un arreglo entregando un único valor como respuesta

La reducción más básica es la **suma agregada**

$$
[0, 1, 2, 4, 3] \rightarrow 0 + 1 + 2 + 4 + 3 = 10 
$$


Algunas de las reducciones disponibles en NumPy son:

- `sum`, `prod`
- `amax`, `amin`, `argmax`, `argmin`
- `mean`, `std`, `var`, `percentile`, `median`
- `cumsum`, `cumprod`

:::{note}

Las reducciones pueden realizar al ndarray completo o a un subconjunto de sus ejes

:::

Diferencia entre sumar en el eje de filas, columnas y suma total:

In [94]:
A = np.tile(np.arange(3), (2, 1))
A

array([[0, 1, 2],
       [0, 1, 2]])

In [95]:
np.sum(A, axis=0)

array([0, 2, 4])

In [96]:
np.sum(A, axis=1)

array([3, 3])

In [97]:
np.sum(A)

6

Encontrar el valor y posición del máximo en un arreglo es también un tipo de reducción

In [98]:
A = np.random.randn(2, 3)
A

array([[-0.70573115, -1.82654396,  0.18613106],
       [-0.32164857, -0.14467746, -1.8050291 ]])

In [99]:
np.amax(A, axis=0) # El valor del máximo en el eje 0 para cada 


array([-0.32164857, -0.14467746,  0.18613106])

Las operaciones de reducción de NumPy son altamente eficientes

Hagamos una pequeña prueba de desempeño sumando  un vector

Usaremos la magia de IPython `@timeit` que nos permite medir tiempo de cómputo

In [ ]:
A = np.arange(100000)

def suma_loop(arreglo):
    suma = 0.
    for elemento in arreglo:
        suma += elemento
    return suma

L = list(A)
%timeit -n10 suma_loop(A)
%timeit -n10 suma_loop(L)
%timeit -n10 sum(A)
%timeit -n10 sum(L)
%timeit -n10 np.sum(L)
%timeit -n10 np.sum(A)

display(np.sum(A))
display(sum(L))

Muchas de estas funciones están implementadas como métodos de la clase arreglo, por ejemplo

In [ ]:
display(A.sum())
display(A.max(axis=0))
display(A.min())

También cuentan con versiones seguras contra NaNs

In [ ]:
A = np.array([1., 10., 2., np.nan])
display(np.sum(A))
display(np.nansum(A))

**Nota:** Si queremos encontrar los NaN en un arreglo podemos usar `isnan` 

In [ ]:
np.isnan(A)

### Operaciones vectorizadas

Son funciones que operan de forma *element-wise* o elemento a elemento

Ya vimos las operaciones aritméticas elemento a elemento pero existen muchas más

Por ejemplo para calcular el valor absoluto de los elementos de un arreglo

In [ ]:
A = np.random.randn(3, 3)
display(A)
np.absolute(A) # Equivalente a np.abs(A)

Exponenciar un arreglo

In [ ]:
x = np.arange(10)
display(np.power(x, 2)) # Equivalente a x**2
display(np.sqrt(x))

Calcular funciones exponencial, logaritmo y trigonométricas  a partir de una arreglo

In [ ]:
x = np.array([0.1, 1., 10.0])
display(np.log(x)) # También está log2, log10
display(np.exp(x)) 
display(np.sin(x)) # También está arcsin, sinh
display(np.cos(x)) # También está arccos, cosh
display(np.tan(x)) #También está arctan, tanh

Otras funciones útiles: 

- Para obtener el signo de cada elemento de un arreglo: `sign`
- Para obtener un arreglo de 1 dividido los elementos del mismo: `reciprocal`
- Para redondear hacia abajo o hacia arriba: `round`, `floor` y `ciel`
- Para obtener la parte real o imaginaria de un número complejo: `real`, `imag`
- O el conjugado de un número complejo: `conj`, 

### Operaciones booleanas 

NumPy soporta operaciones booleanas sobre ndarray

In [ ]:
A = np.arange(6).reshape(2, 3)
display(A)
display(A == 4)
display(np.equal(A, 4))

Como vimos antes podemos crear una máscara booleana para indexar un arreglo

In [ ]:
mask = ~(A % 2 == 0) & (A > 2)
display(mask)
display(A[mask])

La función `where` sirve para recuperar el índice de los elementos que cumplen una cierta condición

In [ ]:
(ixs, iys) = np.where(~(A % 2 == 0) & (A > 2))

for i, j in zip(ixs, iys):
    display("Fila {0} Columna {1} Valor {2}".format(i, j, A[i, j]))

Funciones `any` y `all`

In [ ]:
x = np.random.randn(3, 3)
display(x)
b = (x > 0) & (x**2 > 0.5)
display(b)

display(np.any(b))
display(np.all(b))

### Operaciónes de conjutos

Operaciones de tipo union, intersección y diferencia entre arreglos 1D

Si se les entrega un arreglo de mayor dimensión este se aplanará automaticamente

In [ ]:
A = np.arange(6)
B = np.array([0, 1, 10, 100])
display(A, 
        B)

La unión e intersección, respectivamente:

In [ ]:
display(np.union1d(A, B),
        np.intersect1d(A, B))

O los elementos que existen a A y no en B (y viceversa)

In [ ]:
display(np.setdiff1d(A, B),
        np.setdiff1d(B, A))

### Ordenando arreglos

NumPy provee la función `np.sort` para ordernar un ndarray

Se puede usar el argumento `kind` para escoger distintos algoritmos de ordenamiento (por defecto quicksort)

El argumento `axis` especifica que eje se va a ordenar

In [ ]:
A = np.random.randn(2, 2)
display(A)
display(np.sort(A, axis=1))
display(np.sort(A, axis=0))
display(np.sort(A, axis=None))

La función `np.argsort` entrega un arreglo de índices que ordena el arreglo de menor a mayor

In [ ]:
A = np.array(["A", "B", "C"])
B = np.array([2, 4, 1])

idx = np.argsort(B)
display(idx)
display(A[idx])

**Ordenamiento en memoria de ndarray**

Por defecto un ndarray multidimensional se ordena en memoria siguiente un formato `row-major` similar a la convención usada en `C`. Alternativamente un arreglo se puede guardar en formato `column-major` similar a la convención usada en `Fortran`. La siguiente figura muestra la diferencia

<img src="img/rowcolmajor.png" width="600">

El atributo `order` nos permite seleccionar el ordenamiento al momento de crear el arreglo

También se puede verificar el ordenamiento de un ndarray leyendo su atributo `flags`

- Si tiene el flag `C_CONTIGUOUS` verdadero entonces es `row major`
- Si tiene el flag `F_CONTIGUOUS` verdadero entonces es `column major`


In [ ]:
A = np.array(L)
display(A)
display(A.flags['C_CONTIGUOUS']) # Por defecto es True

A = np.array(L, order='F')
display(A)
display(A.flags['C_CONTIGUOUS'])

El diccionario `flags` contiene los siguientes valores:

In [ ]:
A.flags