# Arreglos n-dimensionales con [NumPy](http://www.numpy.org/)


NumPy es un paquete de computación científica con Python que provee:

- Un objecto contenedor muy versatil: arreglo N-dimensional `ndarray`
- Funciones capaces de hacer *broadcasting*
- Módulos para algebra lineal, Transformada de Fourier, generación de número aleatorios, entre otros
- Herramientas para integrar código C/C++


**Instalación**
    
Con nuestro ambiente conda activado:

    conda install numpy
    
Esto instalará numpy y las librerías de bajo nivel BLAS y MKL

Luego importamos usando

In [1]:
import numpy as np
print("Version: ", np.__version__)

Version:  1.21.2


## Objeto ndarray (alias array)

Una lista `lista` de Python es un tipo de arreglo donde cada elemento puede ser de tipo diferente

:::{warning}

En general es muy ineficiente hacer cálculos numéricos usando listas

:::

Para cálculos numéricos eficientes utilizaremos el objeto `ndarray` de NumPy, que corresponde a un **arreglo n-dimensional de tipo fijo**

La siguiente figura muestra arreglos de Numpy de una, dos y tres dimensiones, respectivamente

<img src="img/ndarray.png" width="500">


Podemos crear un ndarray a partir de 

- una lista o tupla usando `np.array`
- funciones generadoras de NumPy, por ejemplo `np.linspace`, `np.zeros`, etc
- un fichero, por ejemplo usando [`np.genfromtxt`](https://numpy.org/devdocs/user/basics.io.genfromtxt.html) (aunque es preferible utilizar `pandas` en estos casos


In [2]:
# Supongamos que tenemos la siguiente lista de listas
L = [[0, 1, 2], [3, 4, 5]]
print("L es un", type(L))

L es un <class 'list'>


In [3]:
# Podemos transformarla a ndarray con
A = np.array(L)
print("A es un", type(A))
display(A)

A es un <class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5]])

**Atributos básicos de un ndarray**

- El atributo `ndim` es un entero que nos indica el número de dimensiones o ejes del arreglo
- El atributo `shape` es una tupla de entero que nos indica el tamaño del arreglo en cada una de sus dimensiones
- El atributo `dtype` nos indica el tipo del arreglo

En este caso

In [4]:
f"A tiene {A.ndim} dimensiones"

'A tiene 2 dimensiones'

In [5]:
len(A.shape) == A.ndim

True

In [6]:
for d in range(A.ndim):
    print(f"La dimensión {d} tiene largo {A.shape[d]}")

La dimensión 0 tiene largo 2
La dimensión 1 tiene largo 3


In [7]:
f"El arreglo es de tipo {A.dtype}"

'El arreglo es de tipo int64'

Los tipos de dato estándar de NumPy son:

- Enteros: int8, int16, int32, int64
- Enteros sin signo: uint8, uint16, uint32, uint64
- Flotantes (reales): float16, float32, float64, float128
- Números complejos: complex64, complex128, complex256
- Booleanos: Bool

Podemos forzar el tipo al momento de crear usando el argumento `dtype`

In [8]:
display(np.array(L, dtype=np.int16))
display(np.array(L, dtype=np.float32))

array([[0, 1, 2],
       [3, 4, 5]], dtype=int16)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

**Funciones generadoras de ndarray**

Existen algunas funciones de NumPy que permiten crear directamente arreglos con ciertas propiedades

Algunos ejemplos útiles son:

In [9]:
np.zeros(shape=(2, 3), dtype=np.int64) # Arreglo lleno de ceros

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones(shape=(2, 3), dtype=np.float32) # Arreglo lleno con unos

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
np.full(shape=(2, 3), fill_value=np.pi) # Arreglo lleno con un valor arbitrario

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

También existen versiones de estas funciones que copian el tamaño y tipo de otro ndarray

In [12]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

Las siguientes funciones son muy útiles cuando necesitamos crear un rango lineal o logarítmico usando

Se especifica el inicio, el fin y el paso o cantidad de elementos:

In [13]:
np.arange(start=0, stop=5, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
np.linspace(start=0, stop=10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.logspace(start=-1, stop=1, num=5)

array([ 0.1       ,  0.31622777,  1.        ,  3.16227766, 10.        ])

## Manipulación de matrices y vectores

Es usual que antes de operar un ndarray necesitemos cambiar su tamaño o número de dimensiones

Algunas operaciones típicas para modificar la forma de un arreglo son: `reshape`, `tile`, `repeat`, `ravel` y `transpose`

`reshape` reorganice las dimensiones de un arreglo pero debe preservar el tamaño

In [16]:
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [17]:
np.reshape(A, (3, 2)) # Convierte 6 a 3x2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
np.reshape(A, (2, 3)) # Convierte 6 a 2x3

array([[0, 1, 2],
       [3, 4, 5]])

`tile` repite el arreglo en una dirección dada

In [19]:
np.tile(A, (4, 1)) # Repite 4 veces en la dirección de las filas

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [20]:
np.tile(A, (1, 2)) # Repite 2 veces en la dirección de las columnas

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

`repeat` repite cada elemento en una dirección o eje dado

In [21]:
np.repeat(A, 2) # Cada elemento aparece dos veces 

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [22]:
# Cada elemento/fila aparece dos veces en la dirección de las columnas
np.repeat(A.reshape(3, 2), 2, axis=1)

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

`ravel` es una función que aplana el ndarray y retorna un arreglo de una dimensión

In [23]:
# Convierte una matriz de 3x3 en un arreglo de 9
np.ravel(np.zeros(shape=(3, 3)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

`transpose` puede utilizarse para intercambiar la posición de los ejes/dimensiones de un ndarray

Tiene el mismo significado de la trasposición matricial

<img src="img/transpose.jpg" width="300">

Por ejemplo:

In [24]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.transpose(A) # Equivalente a A.transpose() o A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`transpose` puede usarse en ndarrays de cualquier dimensionalidad

Podemos usar el argumento `axes` para especificar cuales dimensiones se van a intercambiar

(Opcionalmente podemos usar la función `np.swapaxes()` para obtener le mismo efecto)

In [26]:
A = np.arange(8).reshape(2, 2, 2)
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
np.transpose(A, axes=(0, 2, 1))

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

**Agregar dimensiones a un arreglo**

En algunas ocasiones nos interesará extender un arreglo, agregándole dimensiones

Consideremos el siguiente arreglo unidimensional

In [28]:
A = np.array([0, 1, 2, 3, 4]) 
print("Dimensión:", A.ndim, ", Tamaño: ", A.shape)

Dimensión: 1 , Tamaño:  (5,)


Como vimos antes podemos agregar una dimensión usando `reshape`, pero otra forma más simple es usando `np.newaxis` (un alias de `None`)

Si queremos agregarle una dimensión al arreglo anterior podemos hacerlo a la derecha o a la izquierda

Por ejemplo agregarle una dimensión a la derecha creará una matriz de $N\times1$ o vector columna

In [29]:
Amod = A[:, np.newaxis]
display(Amod)
print("Dimensión:", Amod.ndim, ", Tamaño: ", Amod.shape)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Dimensión: 2 , Tamaño:  (5, 1)


Mientras que agregarle una dimensión a la izquierda creará una matriz de $1\times N$ o vector fila

In [30]:
Amod = A[np.newaxis, :]
display(Amod)
print("Dimensión:", Amod.ndim, ", Tamaño: ", Amod.shape)

array([[0, 1, 2, 3, 4]])

Dimensión: 2 , Tamaño:  (1, 5)


Algunas operaciones útiles para combinar arreglos son: `concatenate`, `vstack`, `hstack`

`concatenate` es más general que las dos últimas

In [31]:
A = np.arange(5).reshape(1, 5) 
B = np.ones(shape=(1, 5)) 
A, B

(array([[0, 1, 2, 3, 4]]), array([[1., 1., 1., 1., 1.]]))

In [32]:
np.concatenate((A, B), axis=0) # Combinar en eje filas

array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.concatenate((A, B), axis=1) # Combinar en eje columnas

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.]])

In [34]:
np.vstack((A, B)) # Combina siempre en fila

array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.hstack((A, B)) # Combina siempre en columna

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.]])

## Indexación y *slicing*

Al igual que otros contenedores de Python los ndarray soportan *slicing*

:::{note}

Slicing es crear una arreglo a partir de una indexación sobre otro arreglo

:::

Sea por por ejemplo:

In [36]:
L = [[0, 1, 2], [3, 4, 5]]
A = np.array(L)
A

array([[0, 1, 2],
       [3, 4, 5]])

Para acceder al elemento en la segunda fila y primera columna usaríamos

In [37]:
L[1][0]

3

En cambio en Numpy utilizamos

In [38]:
A[1, 0]

3

El ndarray nos da mucha flexibilidad para hacer slicing

In [39]:
A[:, 1] # Retorna la segunda columna

array([1, 4])

In [40]:
A[0, :] # Retorna la primera fila 

array([0, 1, 2])

In [41]:
A[1, ::2] # Retorna los elementos de la primera fila y columnas pares

array([3, 5])

In [42]:
A[-1, -2] # Retorna los elementos de la ultima fila y penultima columna

4

También podemos usar arreglos de enteros para indexar otro arreglo (*fancy indexing*)

In [43]:
ix = np.array([0, 0, 1])
iy = np.array([0, 1, 1])
A[ix, iy] # Elementos [0,0], [0,1] y [1,1]

array([0, 1, 4])

También podemos indexar usando un arreglo de booleanos

In [44]:
A = np.array([0, 2, 1, 3, 4])
B = np.array([True, False, False, True, True])
display(A[B])

array([0, 3, 4])

La siguiente figura muestra de forma esquemática varios ejemplos de slices

<img src="img/slicing.png" width="700">

:::{warning}

Algunas operaciones sobre arreglos no hacen copias (usan referencias)

:::

En particular cuando hacemos un slice, estamos modificando el arreglo original

In [45]:
A = np.arange(100).reshape(10, 10)
B = A
B is A

True

Si modifico A se ve reflejado en B

In [46]:
A[:5, :5] = 100
display(B)

array([[100, 100, 100, 100, 100,   5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100,  15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100,  25,  26,  27,  28,  29],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

Modificaciones en subarreglos (vistas) también son referenciadas

In [47]:
A = np.arange(100).reshape(10, 10)
B = A[:5, :5]
display(B is A)
B[:, :] = 100
display(A)

False

array([[100, 100, 100, 100, 100,   5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100,  15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100,  25,  26,  27,  28,  29],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

Si queremos evitar este comportamiento se puede forzar la creación de una copia con el método `copy()`

In [48]:
B = A.copy()
A[0, 0] = 0
display(B[0])

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

:::{seealso}

Continua a la siguiente página para aprender sobre las operaciones aritméticas que podemos hacer con ndarrays

:::