# Operaciones sobre ndarrays

In [1]:
import numpy as np

## Operaciones aritméticas y *Broadcasting* 

Los ndarray soportan las operaciones aritméticas básicas

- Suma:  +, +=
- Resta: -, -=
- Multiplicación:  *,*= 
- División: /, /=
- División entera: //, //=
- Exponenciación: ** , **=

Estas operaciones tienen un comportamiento element-wise (elemento a elemento), es decir

$$
\pmatrix{0 & 1 \\2 & 3 } \cdot \pmatrix{1 & 5 \\2 & 2 } = \pmatrix{0 & 5 \\4 & 6 }
$$

Veamos algunos ejemplos:

In [2]:
N = 3
A = np.eye(N)
B = np.ones(shape=(N, N))
A, B

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [3]:
A + B 

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [4]:
A*B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

:::{note}

El operador * no corresponde a la multiplicación de matrices sino a la multiplicación elemento por elemento

:::

**Broadcasting**

Cuando los ndarray que estamos operando no son del mismo tamaño se hace un *broadcast*

Por ejemplo si operamos una constante con un arreglo, la constante se opera con cada elemento del arreglo

In [5]:
A - 1

array([[ 0., -1., -1.],
       [-1.,  0., -1.],
       [-1., -1.,  0.]])

Las siguientes son las reglas automáticas de broadcasting

1. Si dos arreglos son de dimensiones distintas la dimensión del más pequeño se agranda con "1"s **por la izquierda**
1. Si dos arreglos tienen tamaños ditintos, el que tiene tamaño "1" se estira en dicha dimensión
1. Si en cualquier dimensión los tamaños son distintos y ninguno es igual a "1" ocurre un error


<img src="img/broadcast.png" width="550">

Imagen tomada del [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/06.00-figure-code.html#Broadcasting)

Observe los siguientes ejemplos y reflexione sobre las reglas de broadcast que se está aplicando en cada caso

In [6]:
C = np.arange(N)
B = np.ones(shape=(N, N))
C, B

(array([0, 1, 2]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [7]:
B+C

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [8]:
B + C.reshape(-1, 1)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [9]:
C.reshape(1, N) + C.reshape(N, 1)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

**Operaciones matriciales**

Antes dijimos que la multiplicación con `*` se realiza elemento a elemento

Para realizar una multiplicación matricial propiamente tal podemos usar `dot` o el operador `@`

In [10]:
A = np.arange(4).reshape(2, 2)
B = np.arange(4)[::-1].reshape(2, 2)
A, B 

(array([[0, 1],
        [2, 3]]),
 array([[3, 2],
        [1, 0]]))

Note la diferencia:

In [11]:
A*B

array([[0, 2],
       [2, 0]])

In [12]:
np.dot(A, B)

array([[1, 0],
       [9, 4]])

Otras operaciones matricionales útiles son:

- `np.inner` que calcula el producto escalar o producto interno
- `np.outer` que calcula el producto externo
- `np.cross` que calcula  cruz

El módulo  [`linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html) de NumPy contiene muchas más funciones de álgebra lineal que nos permiten 

- Calcular matriz inversa, determinantes y trazas
- Resolver sistemas lineales
- Factorizar matrices
- Calcular valores y vectores propios

entre otros. Este módulo será estudiando en una lección siguiente

## Operaciones de reducción

Una **reducción** es una operación que **agrega** los valores de un arreglo entregando un único valor como respuesta

La reducción más básica es la **suma agregada**

$$
[0, 1, 2, 4, 3] \rightarrow 0 + 1 + 2 + 4 + 3 = 10 
$$


Algunas de las reducciones disponibles en NumPy son:

- `sum`, `prod`
- `amax`, `amin`, `argmax`, `argmin`
- `mean`, `std`, `var`, `percentile`, `median`
- `cumsum`, `cumprod`

:::{note}

Las reducciones pueden realizar al ndarray completo o a un subconjunto de sus ejes

:::

Diferencia entre sumar en el eje de filas, columnas y suma total:

In [13]:
A = np.tile(np.arange(3), (2, 1))
A

array([[0, 1, 2],
       [0, 1, 2]])

In [14]:
np.sum(A, axis=0)

array([0, 2, 4])

In [15]:
np.sum(A, axis=1)

array([3, 3])

In [16]:
np.sum(A)

6

Encontrar el valor y posición del máximo en un arreglo es también un tipo de reducción

In [17]:
A = np.random.randn(2, 3)
A

array([[-1.49137569,  0.46936976, -0.25980522],
       [ 0.3859342 , -1.55686259, -0.34882233]])

In [18]:
np.amax(A, axis=0) # El valor del máximo en el eje 0 

array([ 0.3859342 ,  0.46936976, -0.25980522])

In [19]:
np.argmax(A, axis=0) # La posición del máximo en el eje 0 

array([1, 0, 0])

Las operaciones de reducción de NumPy son altamente eficientes

Hagamos una pequeña prueba de desempeño sumando  un vector

Usaremos la magia de IPython `@timeit` que nos permite medir tiempo de cómputo

In [20]:
A = np.arange(100000)

def suma_loop(arreglo):
    suma = 0.
    for elemento in arreglo:
        suma += elemento
    return suma

L = list(A)
%timeit -n10 suma_loop(A)
%timeit -n10 suma_loop(L)
%timeit -n10 sum(A)
%timeit -n10 sum(L)
%timeit -n10 np.sum(L)
%timeit -n10 np.sum(A)

10 ms ± 647 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
7.72 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5.42 ms ± 55.5 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.32 ms ± 27.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.99 ms ± 56.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
48.7 µs ± 5.64 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Y el resultado es por supuesto el mismo

In [21]:
np.allclose(np.sum(A), sum(L))

True

Muchas de estas funciones están implementadas como métodos de la clase arreglo, por ejemplo

In [22]:
display(A.sum())
display(A.max(axis=0))
display(A.min())

4999950000

99999

0

También cuentan con versiones seguras contra NaNs

In [23]:
A = np.array([1., 10., 2., np.nan])
display(np.sum(A))
display(np.nansum(A))

nan

13.0

:::{note}

Si queremos encontrar los NaN en un arreglo podemos usar `isnan` 

:::

In [24]:
np.isnan(A)

array([False, False, False,  True])

## Operaciones vectorizadas

Las operaciones vectorizados son funciones que operan elemento a elemento (*element-wise*)

Ya vimos las operaciones aritméticas elemento a elemento pero existen muchas más

Por ejemplo para calcular el valor absoluto de los elementos de un arreglo

In [25]:
A = np.random.randn(2, 3)
A

array([[ 0.48987236,  1.91565296, -1.50115953],
       [-0.21021931,  0.44430062,  1.26071979]])

In [26]:
np.absolute(A) # Equivalente a np.abs(A)

array([[0.48987236, 1.91565296, 1.50115953],
       [0.21021931, 0.44430062, 1.26071979]])

Exponenciar un arreglo

In [27]:
x = np.arange(5)

In [28]:
np.power(x, 2) # Equivalente a x**2

array([ 0,  1,  4,  9, 16])

In [29]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

Calcular funciones exponencial, logaritmo y trigonométricas  a partir de una arreglo

In [30]:
x = np.array([0.1, 1., 10.0])
np.log(x) # También está log2, log10

array([-2.30258509,  0.        ,  2.30258509])

In [31]:
np.exp(x)

array([1.10517092e+00, 2.71828183e+00, 2.20264658e+04])

In [32]:
np.sin(x), np.cos(x), np.tan(x)

(array([ 0.09983342,  0.84147098, -0.54402111]),
 array([ 0.99500417,  0.54030231, -0.83907153]),
 array([0.10033467, 1.55740772, 0.64836083]))

También existe las versiones 

- hiperbólicas: `sinh`, `cosh`, `tanh`
- inversas: `arcsin`, `arccos` y `arctan`

Otras funciones útiles: 

- El signo de cada elemento de x: `sign(x)`
- Uno dividido los elementos de x : `reciprocal(x)`
- Redondeno hacia abajo o hacia arriba: `round(x)`, `floor(x)` y `ciel(x)`
- Parte real o imaginaria de un número complejo y: `real(y)`, `imag(y)`
- Conjugado de un número complejo: `conj(y)`, 

### Operaciones booleanas 

NumPy soporta operaciones booleanas sobre ndarray

In [33]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
A == 4 # Es un alias de np.equal(A, 4)

array([[False, False, False],
       [False,  True, False]])

Podemos crear una máscara booleana para indexar un arreglo (*fancy indexing*)

In [35]:
mask = ~(A % 2 == 0) & (A > 2)
mask

array([[False, False, False],
       [ True, False,  True]])

In [36]:
A[mask]

array([3, 5])

La función `where` sirve para recuperar el índice de los elementos que cumplen una cierta condición

In [37]:
(ixs, iys) = np.where(~(A % 2 == 0) & (A > 2))

for i, j in zip(ixs, iys):
    display("Fila {0} Columna {1} Valor {2}".format(i, j, A[i, j]))

'Fila 1 Columna 0 Valor 3'

'Fila 1 Columna 2 Valor 5'

Otras funciones útiles

- `any(x)` Para comprobar si al menos un elemento de x es `True`
- `all(x)`: Para comprobar si todos los elementos de x son `True`

In [38]:
x = np.random.randn(2, 3)
x

array([[ 0.40621004,  1.20341154,  0.29600084],
       [-0.63550142, -2.04026409, -0.68395942]])

In [39]:
b = (x > 0) & (x**2 > 0.5)
b

array([[False,  True, False],
       [False, False, False]])

In [40]:
np.any(b)

True

In [41]:
np.all(b)

False

## Operaciónes de conjutos

Operaciones de tipo union, intersección y diferencia entre arreglos 1D

Si se les entrega un arreglo de mayor dimensión este se aplanará automaticamente

In [42]:
A = np.arange(6)
B = np.array([0, 1, 10, 100])
A, B

(array([0, 1, 2, 3, 4, 5]), array([  0,   1,  10, 100]))

La unión e intersección, respectivamente:

In [43]:
np.union1d(A, B)

array([  0,   1,   2,   3,   4,   5,  10, 100])

In [44]:
np.intersect1d(A, B)

array([0, 1])

O los elementos que existen a A y no en B (y viceversa)

In [45]:
np.setdiff1d(A, B)

array([2, 3, 4, 5])

In [46]:
np.setdiff1d(B, A)

array([ 10, 100])

## Ordenando arreglos

NumPy provee la función `np.sort` para ordernar un ndarray

Se puede usar el argumento `kind` para escoger distintos algoritmos de ordenamiento (por defecto quicksort)

El argumento `axis` especifica que eje se va a ordenar

In [47]:
A = np.random.randn(2, 2)
A

array([[-0.57579771, -1.70714159],
       [ 0.50578651,  0.88896311]])

In [48]:
np.sort(A, axis=1)

array([[-1.70714159, -0.57579771],
       [ 0.50578651,  0.88896311]])

In [49]:
np.sort(A, axis=0)

array([[-0.57579771, -1.70714159],
       [ 0.50578651,  0.88896311]])

In [50]:
np.sort(A, axis=None) # Ordena el arreglo aplanado con ravel

array([-1.70714159, -0.57579771,  0.50578651,  0.88896311])

La función `np.argsort` entrega un arreglo de índices que ordena el arreglo de menor a mayor

In [51]:
A = np.array(["A", "B", "C"])
B = np.array([2, 4, 1])
A, B

(array(['A', 'B', 'C'], dtype='<U1'), array([2, 4, 1]))

In [52]:
idx = np.argsort(B)
idx

array([2, 0, 1])

In [53]:
A[idx]

array(['C', 'A', 'B'], dtype='<U1')